Repository brenner-tobias/addon-cloudflared, pull requests merged in 2022-03, with the labels that each got.

#55 Add workflow for automatic Cloudflared updates
  .github/workflows/cloudflare_release.yaml
  cloudflared/Dockerfile
  cloudflared/cloudflared_version.json
  cloudflared/rootfs/build.sh
Labels: ci

#64 Bugfix reading tunnel name from tunnel.json
  cloudflared/rootfs/etc/cont-init.d/10-cloudflared-config.sh
Labels: bugfix

#65 Add Cloudflare Warp routing
  cloudflared/config.yaml
  cloudflared/rootfs/etc/cont-init.d/10-cloudflared-config.sh
Labels: new-feature

#66 Add warp routing documentation
  cloudflared/DOCS.md
Labels: documentation

#69 Add image signing - CAS Codenotary
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  cloudflared/Dockerfile
  cloudflared/build.yaml
  cloudflared/config.yaml
Labels: enhancement

#72 Remove Manager API calls
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/cont-init.d/10-cloudflared-config.sh
Labels: breaking-change

#76 First Stable Release
  README.md
  cloudflared/.README.j2
Labels: major, maintenance

#80 Add check for valid hostname
  cloudflared/rootfs/etc/cont-init.d/10-cloudflared-config.sh
Labels: enhancement
