Repository brenner-tobias/addon-cloudflared, pull requests merged in 2022-09, with the labels that each got.

#172 ⬆️ Update base-image to v12.2.3
  cloudflared/Dockerfile
  cloudflared/build.yaml
Labels: dependencies

#171 Remove add-on healthcheck
  cloudflared/Dockerfile
  cloudflared/build.yaml
  cloudflared/config.yaml
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/dependencies.d/cloudflared
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/finish
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/run
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/type
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/healthcheck
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
Labels: bugfix

#178 ⬆️ Update yq to 4.25.1-r4
  cloudflared/rootfs/build.sh
Labels: dependencies

#180 Fix typo
  cloudflared/DOCS.md
Labels: documentation

#181 Move "docs" in "cloudflare" to include in add-on repository
  cloudflared/DOCS.md
  cloudflared/docs/README.md
  cloudflared/docs/images/1.png
  cloudflared/docs/images/10.png
  cloudflared/docs/images/2.png
  cloudflared/docs/images/3.png
  cloudflared/docs/images/4.png
  cloudflared/docs/images/5.png
  cloudflared/docs/images/6.png
  cloudflared/docs/images/7.png
  cloudflared/docs/images/8.png
  cloudflared/docs/images/9.png
  cloudflared/docs/remote-tunnel.md
  cloudflared/docs/tunnels.md
Labels: documentation

#183 Move docs folder back and add documentation link to github
  cloudflared/DOCS.md
  docs/README.md
  docs/images/1.png
  docs/images/10.png
  docs/images/2.png
  docs/images/3.png
  docs/images/4.png
  docs/images/5.png
  docs/images/6.png
  docs/images/7.png
  docs/images/8.png
  docs/images/9.png
  docs/remote-tunnel.md
  docs/tunnels.md
Labels: documentation

#182 Tidy docs
  cloudflared/DOCS.md
Labels: documentation

#184 Tidy add-on description
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/cloudflared/run
  cloudflared/rootfs/etc/s6-overlay/scripts/01-log-level.sh
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
  cloudflared/translations/en.yaml
  docs/remote-tunnel.md
Labels: documentation

#189 Update docs with mentions of security
  cloudflared/DOCS.md
Labels: documentation

#192 Remove "reset-cloudflared_files" and "quick_tunnel" options
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/cloudflared/run
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
  cloudflared/translations/en.yaml
Labels: documentation, refactor, breaking-change

#193 Change order of configCheck, skip checks if running with custom_config
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
Labels: enhancement
