Repository brenner-tobias/addon-cloudflared, pull requests merged in 2022-08, with the labels that each got.

#134 ⬆️ Update base image to v12.2.2
  cloudflared/Dockerfile
  cloudflared/build.yaml
Labels: dependencies

#132 Log error message if tunnel name doesn't fit
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
Labels: enhancement

#138 Remove custom apparmor.txt | fixes issue on Ubuntu Supervised installations
  cloudflared/apparmor.txt
Labels: bugfix

#137 ⬆️ Update yq to 4.25.1-r3
  cloudflared/rootfs/build.sh
Labels: dependencies

#139 Healthcheck for HA cloudflare tunnel if connection is dropped
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/cloudflared/run
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/dependencies.d/cloudflared
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/finish
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/run
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/type
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/healthcheck
Labels: enhancement

#143 Add watchdog URL
  cloudflared/config.yaml
Labels: enhancement, bugfix

#145 Bugfix watchdog regex
  cloudflared/config.yaml
Labels: bugfix

#147 Add exit code to finish script for watchdog
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/cloudflared/finish
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/finish
Labels: bugfix

#150 Fix spelling of Cloudflare in heading.
  cloudflared/DOCS.md
Labels: documentation

#151 Watchdog - fix metrics server binding
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/cloudflared/run
Labels: bugfix

#153 Alter loglevel of unavailable connection dependent on counter
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/run
Labels: enhancement

#156 Optimize Cloudflare_release Workflow
  .github/workflows/cloudflare_release.yaml
Labels: ci

#157 Dev container update
  .devcontainer.json
  .devcontainer/supervisor.sh
Labels: ci

#160 Enhance issue config file
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#164 Check active network connection first
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/run
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
Labels: enhancement

#167 Change internet check to use netcat and not ping
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/healthcheck/run
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
Labels: bugfix
