Repository brenner-tobias/addon-cloudflared, pull requests merged in 2022-01, with the labels that each got.

#11 Automatically detect HA port
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/cont-init.d/02_cloudflared-setup.sh
Labels: enhancement, minor

#12 Updated Cloudflared + Added Docu for Addon-repo
  README.md
  cloudflared/.README.j2
  cloudflared/DOCS.md
  cloudflared/rootfs/build.sh
  cloudflared/rootfs/etc/cont-init.d/02_cloudflared-setup.sh
  cloudflared/rootfs/etc/services.d/cloudflared/run
Labels: documentation, enhancement, minor

#13 Removed unnecessary init scripts
  cloudflared/rootfs/etc/cont-init.d/00_banner.sh
  cloudflared/rootfs/etc/cont-init.d/01_log-level.sh
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
Labels: enhancement

#17 Extended hosts config
  README.md
  cloudflared/.README.j2
  cloudflared/DOCS.md
  cloudflared/Dockerfile
  cloudflared/apparmor.txt
  cloudflared/config.yaml
  cloudflared/rootfs/build.sh
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
  cloudflared/rootfs/etc/services.d/cloudflared/run
Labels: enhancement, minor, refactor, new-feature

#19 Switch to json config for cloudflared, disabled TLS check
  cloudflared/rootfs/build.sh
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
  cloudflared/rootfs/etc/services.d/cloudflared/run
Labels: enhancement, refactor

#21 Improve additional_hosts example
  cloudflared/DOCS.md
Labels: documentation

#25 Add originRequest support for disableChunkedEncoding flag
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
Labels: minor, new-feature

#24 ✨ Add option to use quick tunnels
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
  cloudflared/rootfs/etc/services.d/cloudflared/run
Labels: documentation, minor

#27 Docu+version update
  cloudflared/DOCS.md
  cloudflared/rootfs/build.sh
Labels: documentation, minor
