Repository brenner-tobias/addon-cloudflared, pull requests merged in 2022-11, with the labels that each got.

#241 ⬆️ Update base image to v12.2.6
  cloudflared/Dockerfile
  cloudflared/build.yaml
Labels: dependencies

#244 Add CODE_OF_CONDUCT.md and CONTRIBUTING.md
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
Labels: documentation

#247 Change security reporting to Security Advisories
  .github/SECURITY.md
Labels: ci

#248 ⬆️ Update base image to 12.2.7
  cloudflared/Dockerfile
  cloudflared/build.yaml
Labels: dependencies

#261 Clarify final URL in docs
  cloudflared/DOCS.md
Labels: documentation
