Repository brenner-tobias/addon-cloudflared, pull requests merged in 2022-10, with the labels that each got.

#203 Make external_hostname and tunnel_name optional
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
  docs/tunnels.md
Labels: priority-low, new-feature, in-progress

#204 Docs tidy
  cloudflared/DOCS.md
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
Labels: documentation

#205 Deprecate warp
  cloudflared/DOCS.md
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
  cloudflared/translations/en.yaml
Labels: documentation

#207 Change order to reflect the default options positions
  cloudflared/config.yaml
Labels: enhancement

#208 Tidy docs
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  cloudflared/DOCS.md
  cloudflared/translations/en.yaml
  docs/tunnels.md
Labels: documentation

#211 Deprecate custom_config
  cloudflared/DOCS.md
  cloudflared/rootfs/build.sh
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
  cloudflared/translations/en.yaml
Labels: documentation

#212 Deprecate 'data_folder'
  cloudflared/DOCS.md
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
  cloudflared/translations/en.yaml
Labels: documentation

#213 set data path for default migration
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
Labels: bugfix

#214 Add creation of dir if not existing
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
Labels: bugfix

#218 Fix YAMLLint warnings in GitHub checks
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/cloudflare_release.yaml
Labels: ci

#217 Remove custom config, data_folder and warp
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/build.sh
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/cloudflared/run
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
  cloudflared/translations/en.yaml
Labels: breaking-change

#228 Tidy docs
  README.md
  cloudflared/DOCS.md
  cloudflared/rootfs/etc/s6-overlay/scripts/10-cloudflared-config.sh
Labels: documentation

#229 Fix list of options in docs
  cloudflared/DOCS.md
Labels: documentation
