Repository brenner-tobias/addon-cloudflared, pull requests merged in 2022-12, with the labels that each got.

#267 Logging and remove legacy check
  cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh
Labels: refactor

#273 Update CI
  .github/workflows/ci.yaml
  .github/workflows/cloudflare_release.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release_updater.yaml
  cloudflared/Dockerfile
  cloudflared/cloudflared_version.json
  cloudflared/rootfs/build.sh
  cloudflared/versions.json
Labels: ci

#278 Bugfix unbound variable
  cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh
Labels: bugfix
