Repository brenner-tobias/addon-cloudflared, pull requests merged in 2022-02, with the labels that each got.

#30 Docu extension for quick tunnel
  cloudflared/DOCS.md
Labels: documentation

#32 Add catch all service option
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
Labels: documentation, minor

#33 Optimize config check
  .github/dependabot.yaml
  .github/release-drafter.yml
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
Labels: enhancement, minor, refactor, ci

#36 Validate config
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
Labels: enhancement, priority-low

#37 Made validation strict to fail if catch_all_service and nginx_proxy_manager are both set
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
Labels: enhancement

#39 Change HA hostname to IP within Docker network
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
Labels: bugfix

#41 Added check for SSL and adaption of protocol
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
Labels: enhancement

#42 Documentation extension for `configuration.yaml`
  cloudflared/DOCS.md
Labels: documentation

#44 Add data_path funcationality & general maintenance
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/cont-init.d/cloudflared-config.sh
  cloudflared/rootfs/etc/services.d/cloudflared/run
Labels: enhancement, new-feature

#49 Log enhancements
  cloudflared/rootfs/etc/cont-init.d/00-cloudflared-log.sh
  cloudflared/rootfs/etc/cont-init.d/10-cloudflared-config.sh
  cloudflared/rootfs/etc/services.d/cloudflared/run
Labels: bugfix

#51 Improve auth successful message
  cloudflared/rootfs/etc/cont-init.d/10-cloudflared-config.sh
Labels: enhancement

#53 Update cloudflared to 2022.2.1
  cloudflared/rootfs/build.sh
Labels: dependencies

#54 Update Cloudflared to 2022.2.2
  cloudflared/rootfs/build.sh
Labels: dependencies
