Repository brenner-tobias/addon-cloudflared, pull requests merged in 2023-03, with the labels that each got.

#336 fix troubleshooting link formatting
  cloudflared/DOCS.md
Labels: documentation

#337 Update base image to v13.1.3
  cloudflared/Dockerfile
  cloudflared/build.yaml
Labels: dependencies

#346 Remove uppercase chars from valid hostnames
  cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh
Labels: enhancement

#347 Update base image to v13.1.4
  cloudflared/Dockerfile
  cloudflared/build.yaml
Labels: dependencies
