Repository brenner-tobias/addon-cloudflared, pull requests merged in 2023-04, with the labels that each got.

#353 Add option in documentation for wildcard DNS record
  cloudflared/DOCS.md
Labels: documentation

#357 Add Post-Quantum to tunnel
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/cloudflared/run
  cloudflared/translations/en.yaml
Labels: enhancement, minor

#362 Revise the documentation
  cloudflared/DOCS.md
Labels: documentation

#360 Auto-Close Renovate "Dependency Dashboard"-Issue
  .github/renovate.json
Labels: maintenance

#365 Allow auto-merge for minor base image updates
  .github/renovate.json
Labels: maintenance

#368 Fix name of Zero Trust dashboard and link in Error Message
  cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh
Labels: documentation

#383 Renovate: auto-merge github-actions
  .github/renovate.json
Labels: maintenance

#389 Revert Cloudflared to 2023.4.1
  cloudflared/Dockerfile
Labels: bugfix
