Repository brenner-tobias/addon-cloudflared, pull requests merged in 2023-01, with the labels that each got.

#290 Update maintenance & license to 2023
  LICENSE.md
  README.md
  cloudflared/.README.j2
  cloudflared/DOCS.md
Labels: maintenance

#295 Update base image to v13.1.0
  cloudflared/Dockerfile
  cloudflared/build.yaml
Labels: dependencies

#296 Introduce GitHub Wiki
  cloudflared/DOCS.md
  docs/README.md
  docs/remote-tunnel.md
  docs/tunnels.md
Labels: documentation

#301 Update base image to v13.1.1
  cloudflared/Dockerfile
  cloudflared/build.yaml
Labels: dependencies

#307 Remove Freenom reference, add wiki link
  README.md
  cloudflared/.README.j2
Labels: documentation
