Repository brenner-tobias/addon-cloudflared, pull requests merged in 2024-03, with the labels that each got.

#608 Add --loglevel as valid run_parameter
  cloudflared/DOCS.md
  cloudflared/config.yaml
Labels: enhancement

#609 Refactor log level logic
  cloudflared/DOCS.md
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/cloudflared/run
  cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh
  cloudflared/translations/de.yaml
  cloudflared/translations/en.yaml
  cloudflared/translations/nl.yaml
Labels: refactor

#612 Remove remnants of armhf and i386 from workflows
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
Labels: ci
