Repository brenner-tobias/addon-cloudflared, pull requests merged in 2024-01, with the labels that each got.

#546 🎉 Happy New Year - update maintenance & license year to 2024
  LICENSE.md
  README.md
  cloudflared/.README.j2
  cloudflared/DOCS.md
Labels: maintenance

#561 Revert "⬆️ Update cloudflare/cloudflared to v2024"
  cloudflared/Dockerfile
Labels: bugfix

#573 Add run_parameters
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/cloudflared/run
  cloudflared/translations/de.yaml
  cloudflared/translations/en.yaml
  cloudflared/translations/nl.yaml
Labels: new-feature

#578 Add add-on config folder mapping
  cloudflared/DOCS.md
  cloudflared/config.yaml
Labels: new-feature
