Repository brenner-tobias/addon-cloudflared, pull requests merged in 2025-05, with the labels that each got.

#825 Add info for other hosting methods
  cloudflared/DOCS.md
Labels: documentation

#828 Add proxy option for local managed tunnels
  cloudflared/DOCS.md
  cloudflared/config.yaml
  cloudflared/rootfs/etc/nginx/template/nginx.conf.gtpl
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/nginx/dependencies.d/init-cloudflared-config
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/nginx/run
  cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh
  cloudflared/translations/de.yaml
  cloudflared/translations/en.yaml
  cloudflared/translations/fr.yaml
  cloudflared/translations/he.yaml
  cloudflared/translations/nl.yaml
  cloudflared/translations/pl.yaml
Labels: new-feature

#832 Write nginx error_log to add-on log
  cloudflared/rootfs/etc/nginx/template/nginx.conf.gtpl
Labels: enhancement

#835 Update Nginx config
  cloudflared/rootfs/etc/nginx/includes/mime.types
  cloudflared/rootfs/etc/nginx/includes/proxy_params.conf
  cloudflared/rootfs/etc/nginx/includes/server_params.conf
  cloudflared/rootfs/etc/nginx/nginx.conf
  cloudflared/rootfs/etc/nginx/servers/.gitkeep
  cloudflared/rootfs/etc/nginx/template/homeassistant.gtpl
  cloudflared/rootfs/etc/nginx/template/nginx.conf.gtpl
  cloudflared/rootfs/etc/s6-overlay/s6-rc.d/nginx/run
Labels: enhancement

#839 Update image for Cloudflare Dashboard
  docs/images/1.png
Labels: documentation
